/*
 * This source file was generated by the Gradle 'init' task
 */
package interpreter;

import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.nio.file.Files;

public class App {
    static BufferedReader r = new BufferedReader(
            new InputStreamReader(System.in));
    static String sourceProgram = "";
    static String jsProgram;
    static Path targetPath = Path.of("main.js");
    static Path sourcePath = Path.of("source.txt");

    static List<String> command = new ArrayList<>();

    public static void main(String[] args) throws Exception {
        String codeLine = " ";
        while (!codeLine.equals("")) {
            System.out.println("Type the code line: ");
            codeLine = r.readLine();
            sourceProgram += codeLine.length() == 0 ? "" : codeLine + "\n";
        }

        jsProgram = Interpreter.interpret(sourceProgram);
        Files.writeString(targetPath, jsProgram);

        // Run .js file
        command.add("node");
        command.add("main.js");
        ProcessBuilder pb = new ProcessBuilder(command);
        Process process = pb.start();

        int exitCode = process.waitFor();
        if (exitCode != 0) {
            System.out.println("Program crashed. Make sure to write the correct program");
            return;
        }

        // Read from .js input stream
        BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
        String line;
        while ((line = reader.readLine()) != null) {
            System.out.println(line);
        }
    }
}
